name: 'Deploy to Heroku'
description: 'Push a backend build or source to a Heroku app'
inputs:
  app-name:
    description: 'Heroku app name'
    required: true
  api-key:
    description: 'Heroku API key'
    required: true
  build-path:
    description: 'Directory that contains the app to deploy (defaults to repo root)'
    required: false
    default: '.'
  image:
    description: 'Image to deploy'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set Working Directory
      shell: bash
      run: |
        echo "Working directory: ${{ inputs.build-path }}"

    - name: Configure Heroku Credentials
      shell: bash
      env:
        HEROKU_API_KEY: ${{ inputs.api-key }}
        HEROKU_APP_NAME: ${{ inputs.app-name }}
      run: |
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login _" >> ~/.netrc
        echo "  password $HEROKU_API_KEY" >> ~/.netrc
        echo "machine git.heroku.com" >> ~/.netrc
        echo "  login _" >> ~/.netrc
        echo "  password $HEROKU_API_KEY" >> ~/.netrc
        chmod 600 ~/.netrc

    - name: Install Heroku CLI
      shell: bash
      run: |
        curl -sSL https://cli-assets.heroku.com/install-ubuntu.sh | sudo bash

    - name: Log in to Heroku Container Registry
      shell: bash
      run: |
        heroku container:login

    - name: Pull Image & Push to Heroku Registry
      shell: bash
      env:
        HEROKU_APP_NAME: ${{ inputs.app-name }}
      run: |
        IMAGE="${{ inputs.image }}"
        docker pull "$IMAGE"
        docker tag "$IMAGE" registry.heroku.com/${HEROKU_APP_NAME}/web
        docker push registry.heroku.com/${HEROKU_APP_NAME}/web

    - name: Release Image
      shell: bash
      env:
        HEROKU_APP_NAME: ${{ inputs.app-name }}
      run: heroku container:release web --app $HEROKU_APP_NAME
