name: 'Deploy Twitch Extension'
description: 'Upload a built Twitch Extension zip to Twitch CDN'
inputs:
  build-path:
    description: 'Directory containing the built extension (will be zipped and uploaded)'
    required: true
  client-id:
    description: 'Twitch Extension Client ID'
    required: true
  client-secret:
    description: 'Twitch Extension Secret'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Zip Extension Build
      shell: bash
      run: |
        cd "${{ inputs.build-path }}"
        zip -r /tmp/extension.zip .

    - name: Upload to Twitch CDN
      shell: bash
      env:
        TWITCH_CLIENT_ID: ${{ inputs.client-id }}
        TWITCH_CLIENT_SECRET: ${{ inputs.client-secret }}
      run: |
        npx --yes twitch-ext-cli upload \
          --id "$TWITCH_CLIENT_ID" \
          --secret "$TWITCH_CLIENT_SECRET" \
          --file /tmp/extension.zip
