name: 'Deploy Twitch Extension'
description: 'Upload a built Twitch Extension zip to Twitch CDN'
inputs:
  build-path:
    description: 'Directory containing the built extension (will be zipped and uploaded)'
    required: true
  client-id:
    description: 'Twitch Extension Client ID'
    required: true
  client-secret:
    description: 'Twitch Extension Secret'
    required: true
  version:
    description: 'Extension version string that already exists in the developer console (e.g. 0.0.1)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Twitch CLI
      shell: bash
      run: |
        set -euo pipefail
        curl -sSL -o /tmp/twitch-cli.tar.gz \
          https://github.com/twitchdev/twitch-cli/releases/download/v1.1.24/twitch-cli_1.1.24_Linux_x86_64.tar.gz
        tar -xzf /tmp/twitch-cli.tar.gz -C /tmp
        BIN=$(sudo find /tmp -maxdepth 2 -type f -name 'twitch' -o -name 'twitch-cli' | head -n1)
        chmod +x "$BIN"
        echo "$(dirname "$BIN")" >> $GITHUB_PATH

    - name: Zip Extension Build
      shell: bash
      working-directory: ${{ inputs.build-path }}
      run: |
        zip -r /tmp/extension.zip .

    - name: Upload to Twitch CDN via Twitch CLI
      shell: bash
      env:
        TWITCH_CLIENT_ID: ${{ inputs.client-id }}
        TWITCH_CLIENT_SECRET: ${{ inputs.client-secret }}
        VERSION: ${{ inputs.version }}
      run: |
        twitch configure --client-id "$TWITCH_CLIENT_ID" --client-secret "$TWITCH_CLIENT_SECRET"
        twitch extensions upload-assets \
          --id "$TWITCH_CLIENT_ID" \
          --version "$VERSION" \
          --file /tmp/extension.zip \
          --yes
