name: Mood Meter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      node-cache-hit: ${{ steps.dep-cache.outputs.cache-hit }}
      envs: ${{ steps.set-env.outputs.envs }}
      backend-image: ${{ steps.backend-image.outputs.image }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine deployment environments
        id: set-env
        run: |
          envs='["Dev"]'
          echo "envs=$envs" >> $GITHUB_OUTPUT
          exit 0

          # For future expansion
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            envs='["Dev"]'
          elif [ "${{ github.event_name }}" = "push" ]; then
            envs='["QA"]'
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            envs='["Prod"]'
          fi

      - name: Setup Node.js & Cache Dependencies
        id: dep-cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint & Unit Tests
        run: |
          npm run lint --if-present
          npm test --if-present

      - name: Build
        run: |
          npm run build -w products/backend
          npm run build -w products/frontend

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: products/frontend/dist/**
          if-no-files-found: error

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend Docker Image
        id: backend-image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/${OWNER}/mood-meter-backend:${{ github.sha }}
          docker build -t "$IMAGE_NAME" -f products/backend/Dockerfile .
          docker push "$IMAGE_NAME"
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Bump Extension Version
        id: version
        working-directory: products/frontend
        run: |
          echo "version=$(npm version patch --no-git-tag-version | sed 's/^v//' | tr -d '\n')" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy - ${{ matrix.environment }}
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ fromJson(needs.prepare.outputs.envs) }}
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-build

      - name: Deploy Twitch Extension
        uses: ./.github/actions/twitch/deploy
        with:
          build-path: frontend-build
          client-id: ${{ secrets.TWITCH_CLIENT_ID }}
          client-secret: ${{ secrets.TWITCH_CLIENT_SECRET }}
          version: ${{ needs.prepare.outputs.version }}

      - name: Deploy Backend API
        uses: ./.github/actions/heroku/deploy
        with:
          image: ${{ needs.prepare.outputs.backend-image }}
          app-name: ${{ secrets.HEROKU_APP_NAME }}
          api-key: ${{ secrets.HEROKU_API_KEY }}

  release:
    name: Create Release
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.prepare.outputs.version }}
          name: Release v${{ needs.prepare.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
