name: Terraform Infra Deploy

on:
  push:
    paths:
      - 'products/infra/**'
      - '.github/workflows/infra-deploy.yaml'
    branches: [main]
  workflow_dispatch:
    inputs:
      app-name:
        description: 'Heroku app name'
        required: true
        default: mood-meter-poc
      app-dynos:
        description: 'Comma-separated list of dynos to deploy'
        required: false
        default: web,poller

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  TF_WORKING_DIR: products/infra
  AWS_REGION: us-east-1
  S3_BUCKET: mood-meter-storage

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Setup Terraform Variables
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo '${{ secrets.TERRAFORM_TF_VARS }}' | base64 --decode > terraform.auto.tfvars
          chmod 600 terraform.auto.tfvars

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init \
            -backend-config="bucket=${{ env.S3_BUCKET }}" \
            -backend-config="key=${{ inputs.app-name }}.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Apply (Heroku App)
        id: tf_app
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply -auto-approve -target=module.mood_meter.heroku_app.this

      - name: Install Heroku CLI
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl -sSL https://cli-assets.heroku.com/install-ubuntu.sh | sudo bash
          heroku authorizations:create --description "github-ci" || true
          heroku auth:whoami

      - name: Ensure Dynos Exist
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ inputs.app-name }}
          DYNO_TYPES: ${{ inputs.app-dynos }}
        run: |
          npm run configure-dynos

      - name: Terraform Apply (Full Stack)
        id: tf_full
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve

      - name: Rollback
        if: failure()
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve
